# Generated by Django 5.2 on 2025-09-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_remove_category_parrent_category_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="categories", verbose_name="avatar"
            ),
        ),
    ]
