# Generated by Django 5.2 on 2025-09-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_category_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="files/%Y/%m/%d/", verbose_name="file"
            ),
        ),
    ]
