# Generated by Django 5.2 on 2025-09-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_file_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="avatar",
            field=models.ImageField(upload_to="products", verbose_name="avatar"),
        ),
    ]
