# Generated by Django 5.2 on 2025-09-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_product_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="file_type",
            field=models.PositiveSmallIntegerField(
                choices=[(2, "video"), (1, "audio"), (3, "pdf")],
                default=2,
                verbose_name="file type",
            ),
            preserve_default=False,
        ),
    ]
